Vagrant.configure("2") do |config|
 
  config.vm.box = "geerlingguy/centos7"

  config.vm.network "private_network", ip: "192.168.33.15"

  config.vm.network "public_network"

  config.vm.provision "shell", inline: <<-SHELL
     yum install httpd wget unzip -y
	 systemctl start httpd 
	 systemctl enable httpd
	 cd /tmp/
	 wget https://www.tooplate.com/zip-templates/2133_moso_interior.zip
	 unzip -o 2133_moso_interior.zip
	 cp -r 2133_moso_interior/* /var/www/html
	 systemctl restart httpd
  SHELL
end
