Vagrant.configure("2") do |config|

  config.vm.box = "geerlingguy/ubuntu2004"
  config.vm.network "private_network", ip: "192.168.33.16"
  config.vm.network "public_network"
  config.vm.box_download_options = {"ssl-no-revoke" => true}

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
	vb.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt install openjdk-11-jdk -y
    sudo apt install maven -y
    curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee \
      /usr/share/keyrings/jenkins-keyring.asc > /dev/null
      
    echo deb [trusted=yes] https://pkg.jenkins.io/debian binary/ https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null

    sudo apt-get update
    sudo apt-get install jenkins -y
  SHELL
end
